### PR TITLE
[traversability_estimation_filters] Replaced deprecated plugin macro.

### PR DESCRIPTION
**Pull request by MarcoSuetterlin**
Backwards compatible. Test were not run yet. If not needed its fine. But will still do that soon.

### CODE REVIEW

**Comment by marco-tranzatto** [comment]
@pleemann why isn't the jenkins status displayed for this PR, even though jenkins has checked it?

**Comment by pleemann** [comment]
@marco-tranzatto fixed, see build status ;)

**Comment by remod** [comment]
Why not into pre-release?

**Comment by samuelba** [comment]
Because master needs to be green too... and it is in pre-release too.

**Pull request merged**
